<?php
/*
 */
?>
<form id="co-shippingtime-form" action="">
    <div id="checkout-shipping-time-load">
       <!-- Content loaded dynamically -->
    </div>
    <script type="text/javascript">
    //<![CDATA[
        var shippingTime = new Shippingtime('co-shippingtime-form', "<?php echo $this->getUrl('checkout/onepage/saveShippingtime') ?>");
        var shippingtimeForm = new VarienForm('co-shippingtime-form');
        function changeTimeRange(store)
        {
            var timeRange = document.getElementById("shippingtime_"+store+":time");
            timeRange.length = 0;
            var shippingDate = document.getElementById("shippingtime_"+store+":date").value;
            var allRange = <?php echo $this->getShippingtimeOption();?>;
            //console.log(range);
            var range = allRange[store][shippingDate];
            for (var r = 0; r < range.length; r++){
                var options = document.createElement("option");
                options.innerHTML = range[r]['label'];
                options.value = range[r]['value'];
                timeRange.appendChild(options);
            }
        }
    //]]>
    </script>


    <div id="datetimepicker" class="input-append date">
     <ul>
         <?php $store_groups = $this->getStoregroups();
             foreach ($store_groups as $key => $store_group){
                $store_groupid=$store_group->getId();
                $store_name =  ($store_group->getStoregroupName()=='Walmart')?'walmart':'fareast';

         ?>
             <li style="width: 400px;display: inline-block;">
                  <span><?php echo $store_group->getStoregroupName()?>:</span>
                  <div class="field">
                      <label for="shippingtime_<?php echo $store_name?>:date" ><?php echo $this->__('Date') ?></label>
                      <div class="input-box" >
                          <?php echo $this->getShippingtimeHtmlDate($store_name,$store_groupid) ?>
                      </div>
                  </div>
                  <div class="field">
                      <label for="shippingtime_<?php echo $store_name?>:time" ><?php echo $this->__('Time Range') ?></label>
                      <div class="input-box" >
                          <?php echo $this->getShippingtimeHtmlTime($store_name,$store_groupid) ?>
                      </div>
                  </div>
              </li>

          <?php }?>

     </ul>
   </div>

    <div class="buttons-set" id="shippingtime-buttons-container">
        <p class="back-link"><a href="#" onclick="checkout.back(); return false;"><small>&laquo; </small><?php echo $this->__('Back') ?></a></p>
        <button type="button" class="button" onclick="shippingTime.save()"><span><span><?php echo $this->__('Continue') ?></span></span></button>
        <span id="shippingtime-please-wait" class="please-wait" style="display:none;">
            <img src="<?php echo $this->getSkinUrl('images/opc-ajax-loader.gif') ?>" alt="<?php echo $this->__('Loading next step...') ?>" title="<?php echo $this->__('Loading next step...') ?>" class="v-middle" /> <?php echo $this->__('Loading next step...') ?>
        </span>
    </div>
</form>
