<?php
/*
 */
?>
<form id="co-shippingtime-form" action="">
    <div id="checkout-shipping-time-load">
       <!-- Content loaded dynamically -->
    </div>
    <script type="text/javascript">
    //<![CDATA[
        var shippingTime = new Shippingtime('co-shippingtime-form', "<?php echo $this->getUrl('checkout/onepage/saveShippingtime') ?>");
    //]]>
    </script>


 <div id="datetimepicker" class="input-append date">
 <ul>
      <?php $store_groups = $this->getStoregroups();
     foreach ($store_groups as $key => $store_group){
     	$store_groupid=$store_group->getId();
      ?>
      <li>
      <span><?php echo $store_group->getStoregroupName()?>:</span>
      <span><?php echo $this->__('From')?></span>
       <input id="shippingtime_start_<?php echo $store_groupid;?>" type="text" style="width:160px;" class=" input-text" value="<?php $store_group->getDeliverStarttime?>" name="shippingtime[<?php echo $store_groupid?>][deliver_starttime]" />
       <img src="<?php echo  $this->getSkinUrl('images/calendar.gif');?>" id="shippingtime_start<?php echo $store_groupid?>_button" class="v-middle"  />
        <script type="text/javascript">
     Calendar.setup({
    inputField: "shippingtime_start_<?php echo $store_groupid; ?>",
    ifFormat: "%Y-%m-%e %H:%M:%S",
    showsTime: true,
    button: "shippingtime_start<?php echo $store_groupid?>_button",
    align: "Bl",
    singleClick : true ,
    });
    </script>
       <span><?php echo $this->__('To')?></span>
       <input type="text" id="shippingtime_end_<?php echo $store_groupid?>" value="<?php $store_group->getDeliverEndtime?>" style="width:160px;" class=" input-text" name="shippingtime[<?php echo $store_groupid?>][deliver_endtime]" />
	<img src="<?php echo  $this->getSkinUrl('images/calendar.gif');?>" id="shippingtime_end<?php echo $store_groupid?>_button" class="v-middle"  />
      <script type="text/javascript">
     Calendar.setup({
    inputField: "shippingtime_end_<?php echo $store_groupid; ?>",
    ifFormat: "%Y-%m-%e %H:%M:%S",
    showsTime: true,
    button: "shippingtime_end<?php echo $store_groupid?>_button",
    align: "Bl",
    singleClick : true ,
    });
    </script>

</li>

      <?php }?>
      
  </ul>
    </div>

    <div class="buttons-set" id="shippingtime-buttons-container">
        <p class="back-link"><a href="#" onclick="checkout.back(); return false;"><small>&laquo; </small><?php echo $this->__('Back') ?></a></p>
        <button type="button" class="button" onclick="shippingTime.save()"><span><span><?php echo $this->__('Continue') ?></span></span></button>
        <span id="shippingtime-please-wait" class="please-wait" style="display:none;">
            <img src="<?php echo $this->getSkinUrl('images/opc-ajax-loader.gif') ?>" alt="<?php echo $this->__('Loading next step...') ?>" title="<?php echo $this->__('Loading next step...') ?>" class="v-middle" /> <?php echo $this->__('Loading next step...') ?>
        </span>
    </div>
</form>
