<?php
/*
 */
?>
<form id="co-shippingtime-form" action="">
    <div id="checkout-shipping-time-load">
       <!-- Content loaded dynamically -->
    </div>
    <script type="text/javascript">
    //<![CDATA[
        var shippingTime = new Shippingtime('co-shippingtime-form', "<?php echo $this->getUrl('checkout/onepage/saveShippingtime') ?>");
    //]]>
    </script>


 <div id="datetimepicker" class="input-append date">
 <ul>
      <?php $store_groups = $this->getStoregroups();
     foreach ($store_groups as $key => $store_group){
     	$store_groupid=$store_group->getId();
        $store_name =  ($store_group->getStoregroupName()=='Walmart')?'walmart':'fareast';

      ?>
      <li>
      <span><?php echo $store_group->getStoregroupName()?>:</span>
      <span><?php echo date('Y-m-d H:i:s')?></span>
      <div class="field">
          <label for="shippingtime_<?php echo $store_name?>:select" ><?php echo $this->__('Date') ?></label>
          <div class="input-box">
              <?php echo $this->getShippingtimeHtmlDate($store_name) ?>
          </div>
      </div>
      <div class="field">
          <label for="shippingtime_<?php echo $store_name?>:select" ><?php echo $this->__('Time Range') ?></label>
          <div class="input-box">
              <?php echo $this->getShippingtimeHtmlSelect($store_name,true,$store_group->getDeliverStarttime()) ?>
          </div>
      </div>


</li>

      <?php }?>
      
  </ul>
    </div>

    <div class="buttons-set" id="shippingtime-buttons-container">
        <p class="back-link"><a href="#" onclick="checkout.back(); return false;"><small>&laquo; </small><?php echo $this->__('Back') ?></a></p>
        <button type="button" class="button" onclick="shippingTime.save()"><span><span><?php echo $this->__('Continue') ?></span></span></button>
        <span id="shippingtime-please-wait" class="please-wait" style="display:none;">
            <img src="<?php echo $this->getSkinUrl('images/opc-ajax-loader.gif') ?>" alt="<?php echo $this->__('Loading next step...') ?>" title="<?php echo $this->__('Loading next step...') ?>" class="v-middle" /> <?php echo $this->__('Loading next step...') ?>
        </span>
    </div>
</form>
