<form id="co-tips-form" action="">
<fieldset>
    <ul class="form-list">
    <li id="tips-form">
        <fieldset>
            <ul>
                <li class="wide">
                    <label for="tips:like" class="required"><em>*</em><?php echo $this->__('Do you like this post?') ?></label>
                    <div class="input-box">
                        <input type='text' name='tips[like]'  class="required-entry input-text" id="tips:like" value='<?php echo $this->getQuote()->getTipsLike()?>'/>
                    </div>
                </li>
            </ul>
        </fieldset>
     </li>
    </ul>
    <div class="buttons-set" id="tips-buttons-container">
        <p class="required"><?php echo $this->__('* Required Fields') ?></p>
        <button type="button" title="<?php echo $this->__('Continue') ?>" class="button" onclick="tips.save()"><span><span><?php echo $this->__('Continue') ?></span></span></button>
        <span class="please-wait" id="tips-please-wait" style="display:none;">
            <img src="<?php echo $this->getSkinUrl('images/opc-ajax-loader.gif') ?>" alt="<?php echo $this->__('Loading next step...') ?>" title="<?php echo $this->__('Loading next step...') ?>" class="v-middle" /> <?php echo $this->__('Loading next step...') ?>
        </span>
    </div>
</fieldset>
</form>
<script type="text/javascript">
//<![CDATA[
    var tips = new TipsMethod('co-tips-form','<?php echo $this->getUrl('checkout/onepage/saveTips') ?>');
    var tipsForm = new VarienForm('co-tips-form');
//]]>
</script>
