<form id="co-tips-form" action="">
<fieldset>
    <ul class="form-list">
    <li id="tips-form">
        <fieldset>
            <ul>
                <!--<li class="fields">
                    <div class="field">
                        <label for="tips:select" ><?php echo $this->__('Tips') ?></label>
                        <div class="input-box">
                            <?php echo $this->getTipsHtmlSelect('tips') ?>
                        </div>
                    </div>
                </li>-->
                <li class="wide">
                    <label for="tips:other" class=""><?php echo $this->__('Tips are a great way to encourage your shopper and appreciate his/her work! 100% of tips go to them. Thank you!') ?></label>
                    <div class="input-box">
                        <input style="width:100px" type='text' name='tips[other]'  class="input-text" id="tips:other" value='<?php echo $this->getQuote()->getOther()?>'/>
                    </div>
                </li>
            </ul>
        </fieldset>
     </li>
    </ul>
    <div class="buttons-set" id="tips-buttons-container">
        <p class="back-link"><a href="#" onclick="checkout.back(); return false;"><small>&laquo; </small><?php echo $this->__('Back') ?></a></p>
        <button type="button" title="<?php echo $this->__('Continue') ?>" class="button" onclick="tips.save()"><span><span><?php echo $this->__('Continue') ?></span></span></button>
        <span class="please-wait" id="tips-please-wait" style="display:none;">
            <img src="<?php echo $this->getSkinUrl('images/opc-ajax-loader.gif') ?>" alt="<?php echo $this->__('Loading next step...') ?>" title="<?php echo $this->__('Loading next step...') ?>" class="v-middle" /> <?php echo $this->__('Loading next step...') ?>
        </span>
    </div>
</fieldset>
</form>
<script type="text/javascript">
//<![CDATA[
    var tips = new TipsMethod('co-tips-form','<?php echo $this->getUrl('checkout/onepage/saveTips') ?>');
    var tipsForm = new VarienForm('co-tips-form');
//]]>
</script>
