<?php

/** @var Algolia_Algoliasearch_Helper_Config $config */
$config = Mage::helper('algoliasearch/config');

/** @var Mage_Customer_Model_Session $session */
$session = Mage::getSingleton('customer/session');
$group_id = $session->getCustomerGroupId();

$currency_code = Mage::app()->getStore()->getCurrentCurrencyCode();
$price_key = $config->isCustomerGroupsEnabled(Mage::app()->getStore()->getStoreId()) ? '.'.$currency_code.'.group_'.$group_id : '.'.$currency_code.'.default';
?>

<!-- Product hit template -->
<script type="text/template" id="instant-hit-template">
    {{#hits}}
        <div class="ui modal" id="modal_{{objectID}}" style="height:650px;overflow-y: auto">
            <div class="content">
                <div style="margin-bottom: 25px;">
                    <i class="close icon"></i>
                    <span style="color: #65c178" class="departments"></span>
                </div>
                <div class="ui two column grid">
                    <div class="column">
                        <div id="image_block_{{objectID}}">
                            <img  style="width: 100%" id="main_image_{{objectID}}" class="ui bordered image" src="" data-image="" >
                        </div>
                        <div style="margin-top: 20px" id="image_lightbox_{{objectID}}">
                            <ul>
                            </ul>
                        </div>
                    </div>
                    <div class="column">
                        <div>
                            <p class="p_name"></p>
                            <p><span style="font-weight: bolder;color: #65c178;font-size: 18px" class="span_price"></span> <span style="float:right" class="span_quantity"></span></p>
                        </div>
                        <div class="ui divider ui-divider"></div>
                        <div>
                            <h4>Description</h4>
                            <p class="p_desc"></p>
                        </div>
                    </div>
                </div>
            </div>
        </div>

        <div class="col-md-4 col-sm-6">
            <div class="result-wrapper">
                <div href="" class="result algolia-clearfix">
                    <div class="result-content">
                        <div class="result-thumbnail" onclick="openModel(this)" data-productid="{{objectID}}">
                            {{#image_url}}<img src="{{{ image_url }}}"/>{{/image_url}}
                            {{^image_url}}<span class="no-image"></span>{{/image_url}}
                        </div>
                        <div class="result-sub-content">
                            <h3 class="result-title text-ellipsis">
                                {{{ _highlightResult.name.value }}}
                            </h3>
                            <div class="ratings">
                                <div class="ratings-wrapper">
                                    <!--<div class="ratings-sub-content">-->
                                        <!--<div class="rating-box">-->
                                            <!--<div class="rating" style="width:{{rating_summary}}%" width="148" height="148"></div>-->
                                        <!--</div>-->
                                    <!--</div>-->
                                    <div class="price">
                                        <div class="price-wrapper">
                                            <div>
                                                <span
                                                    class="after_special {{#price<?php echo $price_key; ?>_original_formated}}promotion{{/price<?php echo $price_key; ?>_original_formated}}">
                                                    {{price<?php echo $price_key; ?>_formated}}
                                                </span>

                                                {{#price<?php echo $price_key; ?>_original_formated}}
                                                    <span class="before_special">
                                                        {{price<?php echo $price_key; ?>_original_formated}}
                                                    </span>
                                                {{/price<?php echo $price_key; ?>_original_formated}}
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                            <div class="result-description text-ellipsis">{{{ _highlightResult.description.value }}}</div>

                            {{#isAddToCartEnabled}}
                                {{#in_stock}}
                                    <!--<form action="<?php echo Mage::getBaseUrl(); ?>/checkout/cart/add/product/{{objectID}}"-->
                                          <!--method="post">-->
                                        <!--<input type="hidden" name="form_key"-->
                                               <!--value="<?php echo Mage::getSingleton('core/session')->getFormKey(); ?>"/>-->
                                        <!--<input type="hidden" name="qty" value="1">-->
                                        <!--<button type="submit"><?php echo $this->__('Add to Cart'); ?></button>-->
                                    <!--</form>-->
                                    <button onclick="add_to_cart(this)" class="button add-cart-button" type="submit" data-productid="{{objectID}}"><?php echo $this->__('Add to Cart'); ?></button>
                                {{/in_stock}}
                            {{/isAddToCartEnabled}}
                        </div>
                    </div>
                </div>
            </div>
        </div>
    {{/hits}}
</script>