<?php

/** @var Algolia_Algoliasearch_Helper_Config $config */
$config = Mage::helper('algoliasearch/config');

$title = '';
$description = '';
$content = '';
$imgHtml = '';

if ($config->isInstantEnabled() && $config->replaceCategories() && Mage::app()->getRequest()->getControllerName() == 'category') {
    $category = Mage::registry('current_category');
    $title = $category->getName();

    if ($category && $category->getDisplayMode() !== 'PAGE') {
        $category->getUrlInstance()->setStore(Mage::app()->getStore()->getStoreId());

        if ($category->getDisplayMode() == 'PRODUCTS_AND_PAGE') {
            $page = $category->getLandingPage();
            $cms_block = Mage::getModel('cms/block')->load($page);

            $description = $category->getDescription();
            $content = $this->getLayout()->createBlock('cms/block')->setBlockId($page)->toHtml();

            if ($category->getImageUrl()) {
                $imgHtml = '<p class="category-image"><img src="'.$category->getImageUrl().'" alt="'.$this->escapeHtml($category->getName()).'" title="'.$this->escapeHtml($category->getName()).'" /></p>';
                $imgHtml = $this->helper('catalog/output')->categoryAttribute($category, $imgHtml, 'image');
            }
        }
    }
}

$helper =  Mage::helper('algoliasearch/data');
$token = $helper->getToken();
echo '<input type="hidden" value="'.$token.'" id="token">';

?>

<!-- Instantsearch wrapper template -->
<script type="text/template" id="instant_wrapper_template">
    {{#findAutocomplete}}
    <div id="algolia-autocomplete-container"></div>
    {{/findAutocomplete}}
    <div id="algolia_instant_selector" class="<?php echo count($config->getFacets()) > 0 ? ' with-facets' : '' ?>">

        <?php if ($title || $imgHtml || $description || $content): ?>
            <div class="row">
                <div class="col-md-12">
                    <div id="algolia-static-content">
                        <div class="page-title category-title">
                            <h1><?php echo $title; ?></h1>
                        </div>
                        <div>
                            <?php echo $imgHtml; ?>
                        </div>
                        <div class="category-description std">
                            <?php echo $description; ?>
                        </div>
                        <?php echo $content; ?>
                    </div>
                </div>
            </div>
        <?php endif; ?>

        <div class="row">
            <div class="col-md-3" id="algolia-left-container">
                <div id="refine-toggle" class="visible-xs visible-sm">+ <?php echo $this->__('Refine'); ?></div>
                <div class="hidden-xs hidden-sm" id="instant-search-facets-container">
                    <div id="current-refinements"></div>
                </div>
            </div>

            <div class="col-md-9" id="algolia-right-container">
                <div class="row">
                    <div class="col-md-12">
                        <div>
                            {{#second_bar}}
                            <div id="instant-search-bar-container">
                                <div id="instant-search-box">
                                    <div class="instant-search-bar-label">
                                        <span class="icon"></span>
                                        <span><?php echo $this->__('Current search'); ?></span>
                                    </div>
                                    <div class="instant-search-bar-wrapper">
                                        <label for="instant-search-bar">
                                            <?php echo $this->__('Search:'); ?>
                                        </label>

                                        <input placeholder="<?php echo $this->__('Search for products'); ?>"
                                               id="instant-search-bar" type="text" autocomplete="off" spellcheck="false"
                                               autocorrect="off" autocapitalize="off"/>

                                        <span class="clear-cross clear-query-instant"></span>
                                    </div>
                                </div>
                            </div>
                            {{/second_bar}}
                        </div>
                    </div>
                </div>
                <div class="row algolia-clearfix">
                    <div>
                        <div class="hits">
                            <div class="infos algolia-clearfix">
                                <div class="pull-left" id="algolia-stats"></div>
                                <div class="pull-right">
                                    <div class="sort-by-label pull-left">
                                        <?php echo $this->__('SORT BY'); ?>
                                    </div>
                                    <div class="pull-left" id="algolia-sorts"></div>
                                </div>
                            </div>
                            <div id="instant-search-results-container"></div>
                        </div>
                    </div>
                </div>

                <div class="text-center">
                    <div id="instant-search-pagination-container"></div>
                </div>
            </div>
        </div>

    </div>
</script>
<script>
    function add_to_cart(target){
        var token =  $jq("#token").val();
        var product_id = target.getAttribute("data-productid");

        var data = {"product_id":product_id,"qty":1};
        if (token){
            $jq.ajax({
                type:"put",
                url:"https://cartgogogo.com/custom/api/mobile/api.php/cart/add",
                data:"products="+JSON.stringify(data),
                headers: {
                    'Content-Type': 'application/x-www-form-urlencoded; charset=UTF-8',
                    'Authorization': token
                },
                success:function(res){
                    console.log(res);
                    res = eval("("+res+")");
                    if(res.success == 1){
                        window.location.href = "https://cartgogogo.com/checkout/cart";
                    }
                }
            });
        }else{
            window.location.href = "https://cartgogogo.com/customer/account/login/";
        }
    }

    function openModel(target){
        var product_id = target.getAttribute("data-productid");
        $jq.ajax({
            type:"get",
            url:"https://cartgogogo.com/custom/api/mobile/api.php/category/product",
            data:"product_id="+product_id,
            headers: {
                'Content-Type': 'application/x-www-form-urlencoded; charset=UTF-8'
            },
            success:function(res){
                res = eval("("+res+")");
                if(res.success == 1){
                    var main_image = $jq("#main_image_"+product_id);
                    main_image.attr("src",res.data.image_default);
                    $jq("#modal_"+product_id+" .departments").html(res.data.category_name+" > "+ res.data.name);
                    $jq("#modal_"+product_id+" ul").html(res.data.thumb_string);
                    $jq("#modal_"+product_id+" .span_price").html(res.data.price_string);
                    $jq("#modal_"+product_id+" .span_quantity").html(res.data.quantity);
                    $jq("#modal_"+product_id+" .p_desc").html(res.data.description);
                    $jq("#modal_"+product_id+" .p_name").html(res.data.name);
                    $jq("#modal_"+product_id).modal("show");
                    $jq("#image_block_"+product_id).trigger('zoom.destroy');
                    $jq("#image_block_"+product_id).zoom();
                    $jq('#image_lightbox_'+product_id).unslider({
                        arrows:{
                            prev: '<a class="unslider-arrow prev">Previous</a>',
                            next: '<a class="unslider-arrow next">Next</a>'
                        }
                    });
                    $jq(".thumb-image").unbind("click").click(function(tar){
                        main_image.attr("src",tar.currentTarget.dataset.image);
                        $jq(".zoomImg").attr("src",tar.currentTarget.dataset.image);
                    })
                    if($jq('#image_lightbox_'+product_id+" li img").length >5){

                        $jq(".unslider-arrow").show({
                            duration:100
                        });
                    }else{
                        $jq(".unslider-arrow").hide({
                            duration:100
                        });
                    }
                    $jq(".close.icon").unbind("click").click(function(target){
                        $jq(".ui.modal").modal("hide");
                    })
                }
            }
        });

    }


</script>
<style>
    .ui-divider{
        background: none;
    }
</style>