<style>
    th{
        text-align: center;
        color: #65c178;
        font-size:16px;
        font-weight: bold;
    }

    td{
        text-align: left;
        margin-top: 15px;
        line-height: 30px;
        padding-left: 10px;
        padding-right: 10px;
    }

    .border_right{
        border-right:1px solid #bababa ;
    }

    .circle{
        bottom: 0;
        color: #fff;
        display: inline-block;
        height: 20px;
        left: 0;
        line-height: 20px;
        margin: auto;
        text-align: center;
        top: 0;
        width: 20px;
        border-radius: 20px;
        font-weight: bold;
    }

    .green{
        background: #65c178 none repeat scroll 0 0;
    }

    .grey{
        background: #bababa none repeat scroll 0 0;
    }

    .square{
        border-radius: 0px;
    }

    .mini{
        height: 15px;
        width: 15px;
        line-height: 15px;
        margin-right: 5px;
    }
</style>
<div >
    <div>
        <img src="<?php echo $this->getSkinUrl('cartgogogo/images/delivery_banner.png')?>" style="height:120px;width: 100%">
    </div>
    <div style="text-align: center;margin-top: 25px">
        <b>Walmart Shipping Time Range</b>
    </div>
    <?php
    $date = $this->getShippingtimeDate('walmart','date');
    $range = $this->getShippingtimeDate('walmart','range');
    $date = $this->format_date($date);
    ?>

<!--    <p>-->
<!--        --><?php
//            print_r($date[2]);
//            print_r($range[2]);
//        ?>
<!--    </p>-->

    <table style="width: 100%;margin-top:20px; ">
        <?php
        echo "<tr>";
        for($i = 0;$i < 3;$i++){
            echo '<th colspan="2">'.$date[$i].'</th>';
        }
        echo "</tr>";

        for($i = 0;$i < 6;$i++){
            echo "<tr>";
            $x = $i + 9;
            for($j = 0;$j<3;$j++){
                $r = $range[$j];
                if (in_array($x,$r)){
                    $button = "<span class='circle green square mini'>A</span>";
                }else{
                    $button = "<span class='circle grey square mini'>U</span>";
                }
                if (in_array($x+6,$r)){
                    $button2 = "<span class='circle green square mini'>A</span>";
                }else{
                    $button2 = "<span class='circle grey square mini'>U</span>";
                }

                if ($x < 11){
                    echo "<td>".$button.($x).":00 am - ".($x+1).":00 am </td>";
                }elseif ($x == 11){
                    echo "<td>".$button.($x).":00 am - ".($x+1).":00 noon </td>";
                }elseif ($x == 12){
                    echo "<td>".$button.($x).":00 noon - ".($x+1-12).":00 pm </td>";
                }else{
                    echo "<td>".$button.($x-12).":00 pm - ".($x+1-12).":00 pm </td>";
                }
                if ($j == 2){
                    echo "<td>".$button2.($x+6-12).":00 pm - ".($x+6+1-12).":00 pm </td>";
                }else{
                    echo "<td class='border_right'>".$button2.($x+6-12).":00 pm - ".($x+6+1-12).":00 pm </td>";
                }
            }
            echo "</tr>";
        }
        ?>
    </table>
    <div style="margin-left: 20px;margin-top: 25px">
        <span class='circle green square'>A</span><span style='font-size: 14px;margin-left: 5px'>Available</span>
        <span class='circle grey square' style='margin-left: 25px'>U</span><span style='font-size: 14px;margin-left: 5px'>Unavailable</span>
    </div>
    <div style="margin-left: 20px;margin-top: 25px">
        <span class="circle green">!</span><span style="font-size: 15px;margin-left: 5px">Delivery times are subject to change.</span>
    </div>

<!--    <div class="cattop">-->
<!--        <h2 class="cattop-title">--><?php //echo $this->getTopCfg('title')?><!--</h2>-->
<!--        <li class="">-->
<!--            --><?php
//            for($i = 0;$i < 3;$i++){
//                $ranges = $range[$i];
//                $str = '';
//
//                echo '<div style="width:90%">';
//                echo '<div style="width:15%;font-size: 16px;font-family: OpenSansBold;text-transform: uppercase;font-weight: normal;color: #444;">'.$date[$i].'</div>';
//                foreach ($ranges as $r){
//                    echo '<div style = "width:25%;float:left">'.$this->to12HourRange($r).'</div>';
//                }
//                echo '<br>';
//                echo '</div>';
//            }
//            ?>
<!---->
<!--        </li>-->
<!---->
<!--    </div>-->
</div>
